### ISSUE TITLE
Duplicate btn missing in collections tree view

### ISSUE THREAD

**Issue by Pfeifakopf** [doublethreedigital/duplicator#2]
You can not duplicate entries, when you have ordered collections and use the tree view. You have to toggle the view, to get the button.
![image](https://user-images.githubusercontent.com/3351449/87220627-dcb23080-c365-11ea-88a0-f92c4d1c1a61.png)

**Comment by damcclean** [comment]
This looks like a Statamic issue to me, seems like its hard coded. I'll have a look into getting it working in core.

**Comment by damcclean** [comment]
Sorry for not catching up on this issue until now...

Apparently, it's intentional that custom actions (like the one created by Duplicator) don't show in Tree view. See https://github.com/statamic/cms/issues/2068#issuecomment-698520143

I see where you're coming from that it would be nice to have there but if it's not meant to work that way, I'm not going to argue 😅

Thanks for creating the issue in the first place. Hopefully you have a nice day :)

**Comment by edalzell** [comment]
For others that encounter this, here's the Statamic core FR: https://github.com/statamic/ideas/issues/575
